name: truyendex-syncer

services:
  mongodb:
    image: mongo
    container_name: truyendex-syncer-mongodb
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      # seeding scripts
      - ./devops/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./devops/data/mongo/:/data/
