version: '3.6'
# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up


services:
  my-mongodb:
    image: mongo
    container_name: truyendex-syncer-mongodb
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      # seeding scripts
      - ./devops/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./devops/data/mongo/:/data/
